language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - pip install --upgrade pip
  - pip install --upgrade importlib-metadata
install:
  - pip install -r requirements.txt
script:
  - make lint test
after_success:
  - coveralls
